version: "3.7"

networks:
  source-verify:

x-project-base:
  &project-base
  env_file:
  - .env
  restart: always
  networks:
  - source-verify    

services:
  ui:
    <<: *project-base
    image: ethereum/source-verify:ui-${TAG}
    container_name: ui-${TAG}
    environment:
      VIRTUAL_HOST: ${FQDN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${UI_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
    - "${UI_EXTERNAL_PORT}:${UI_PORT}"
