aliases:
  - &docker-base
    docker:
      - image: circleci/node:10.19.0-buster
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - setup_remote_docker
      - run:
          name: Build and push docker images
          command: |
            CIRCLE_BRANCH=${CIRCLE_BRANCH} ./scripts/build_and_publish_docker_images.sh
  - &filter-base
    filters:
      branches:
        only:
          - staging
          - master
  - &node-base
    working_directory: ~/source-verify
    docker:
      - image: circleci/node
    parameters:
      run_coveralls:
        type: boolean
        default: false
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: install dependencies
          command: npx lerna bootstrap
      - run:
          name: lint
          command: npm run lint
      - run:
          name: tsc and test
          command: npx lerna run build && npx lerna run test
  - &monitor-e2e-base
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install node-fetch dotenv
          command: npm install node-fetch dotenv
      - run:
          name: monitor test
          command: ./scripts/monitor_ci.sh
          no_output_timeout: 30m

version: 2
workflows:
  version: 2
  build_publish_deploy_docker:
    jobs:
      - build-push-ipfs:
          filters:
            branches:
              only:
                - staging
                - master
      - build-push-monitor:
          filters:
            branches:
              only:
                - staging
                - master
      - build-push-repository:
          filters:
            branches:
              only:
                - staging
                - master
      - build-push-s3:
          filters:
            branches:
              only:
                - staging
                - master
      - build-push-server:
          filters:
            branches:
              only:
                - staging
                - master
      - build-push-ui:
          filters:
            branches:
              only:
                - staging
                - master
      - build-push-ui-draft:
          filters:
            branches:
              only:
                - staging
      - deploy:
          filters:
            branches:
              only:
                - staging
                - master
          requires:
            - build-push-ipfs
            - build-push-monitor
            - build-push-repository
            - build-push-s3
            - build-push-server
            - build-push-ui
            - build-push-ui-draft
      - monitor-e2e:
          filters:
            branches:
              only:
                - staging
                - master
          requires:
            - deploy
      - verification-e2e:
          filters:
            branches:
              only:
                - staging
                - master
          requires:
            - deploy

  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - npm-publish:
          filters:
            branches:
              only:
                - master
          requires:
            - node-v10
            - node-v12

  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *" # 1am UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - monitor-e2e
      - verification-e2e

jobs:
  build-push-ipfs:
    <<: *docker-base
    environment:
      SERVICE: "ipfs"
  build-push-localchain:
    <<: *docker-base
    environment:
      SERVICE: "localchain"
  build-push-monitor:
    <<: *docker-base
    environment:
      SERVICE: "monitor"
  build-push-repository:
    <<: *docker-base
    environment:
      SERVICE: "repository"
  build-push-s3:
    <<: *docker-base
    environment:
      SERVICE: "s3"
  build-push-server:
    <<: *docker-base
    environment:
      SERVICE: "server"
  build-push-ui:
    <<: *docker-base
    environment:
      SERVICE: "ui"
  build-push-ui-draft:
    <<: *docker-base
    environment:
      SERVICE: "ui-draft"
  deploy:
    docker:
      - image: circleci/node:10.19.0-buster
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "a9:2f:97:c3:64:10:80:c7:8e:2f:db:f7:a3:4a:53:66"
      - run:
          name: Deploy
          no_output_timeout: 30m
          command: |
            CIRCLE_BRANCH=${CIRCLE_BRANCH} ./scripts/deploy.sh
  node-v10:
    <<: *node-base
    docker:
      - image: circleci/node:10
  node-v12:
    <<: *node-base
    docker:
      - image: circleci/node:12
    environment:
      run_coveralls: "true"
  monitor-e2e:
    <<: *monitor-e2e-base
    docker:
      - image: circleci/node:10
  verification-e2e:
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install dotenv
          command: npm install dotenv
      - run:
          name: verification test
          command: ./scripts/verification-e2e.sh
    docker:
      - image: circleci/node:12
  npm-publish:
    working_directory: ~/source-verify
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npx lerna bootstrap
      - run:
          name: build everything
          command: npx lerna run build
      - run:
          name: Publish npm package
          command: ./scripts/publish_to_npm.sh
