# Config that filters the build jobs: only run new builds for the paths that are changed.
# Runs the continue_config.yml subsequently.
version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# Pipeline parameters for nightly and regular test chain triggers.
parameters:
  run-nightly:
    type: boolean
    default: false
  run-test-chains-regularly:
    type: boolean
    default: false

# the path-filtering orb is required to continue a pipeline based on
# the path of an updated fileset see https://circleci.com/docs/2.0/using-dynamic-configuration/
orbs:
  path-filtering: circleci/path-filtering@0.1.1
  continuation: circleci/continuation@0.3.1

# Can add multiple workflows in setup since only one of these will run. Otherwise it's not possible: https://support.circleci.com/hc/en-us/articles/360060934851--Max-number-of-workflows-exceeded-error
workflows:
  always-run:
    # Don't run on scheduled pipelines and only on master or staging.
    when:
      and:
        - not: << pipeline.parameters.run-nightly >>
        - not: << pipeline.parameters.run-test-chains-regularly >>
        - or: 
          - equal: [ master, << pipeline.git.branch >> ]
          - equal: [ staging, << pipeline.git.branch >> ]
    jobs:
      # the path-filtering/filter job determines which pipeline parameters to update.
      - path-filtering/filter:
          name: check-updated-modules
          # h5ai-nginx without /.* part since it's a submodule. git diff outputs the folder name only, not files under it
          mapping: |
            services/ipfs/.* run-build-ipfs true
            services/s3sync/.* run-build-s3 true
            h5ai-nginx run-build-repository true 
            src/.* run-build-server true
            packages/.* run-build-server true
            environments/.* run-build-server true
            scripts/.* run-build-server true
            package.json run-build-server true
            ui/.* run-build-ui true
          # Compare against the last build of the branch not the default "main" branch
          base-revision: << pipeline.git.base_revision >>
          config-path: .circleci/continue_config.yml

  new-branch:
    when:
      and:
          - not: << pipeline.parameters.run-nightly >>
          - not: << pipeline.parameters.run-test-chains-regularly >>
          - not:
              equal: [ master, << pipeline.git.branch >> ]
          - not:
              equal: [ staging, << pipeline.git.branch >> ]
    jobs:
      - continuation/continue:
          name: continue-new-branch
          configuration_path: .circleci/new_branch.yml

  nightly:
    when: << pipeline.parameters.run-nightly >>
    jobs:
      - continuation/continue:
          name: continue-nightly
          configuration_path: .circleci/nightly.yml

  test-chains-regularly:
    when: << pipeline.parameters.run-test-chains-regularly >>
    jobs: 
      - continuation/continue:
          name: continue-test-chains-regularly
          configuration_path: .circleci/test-chains-regularly.yml
