version: 2.1

# Parameter that can be passed in this pipeline have to be defined here too. Used with nightly.
parameters:
  run-nightly:
    type: boolean
    default: false

aliases:
  - &monitor-e2e-base
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install node-fetch dotenv
          command: npm install node-fetch dotenv
      - run:
          name: monitor test
          command: ./scripts/monitor_ci.sh
          no_output_timeout: 30m
    docker:
      - image: cimg/node:16.15
  - &verification-e2e-base
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install dotenv
          command: npm install dotenv
      - run:
          name: verification test
          command: ./scripts/verification-e2e.sh
      - store_artifacts:
          path: ./verified-contracts
    docker:
      - image: cimg/node:16.15

workflows:
  e2e-tests:
    jobs:
      - monitor-e2e-goerli
      - monitor-e2e-sepolia
      - verification-e2e-goerli
      - verification-e2e-sepolia
  s3-backup-check:
    jobs:
      - check-s3-backup
  etherscan-instances:
    jobs:
      - check-etherscan-instances

jobs:
  monitor-e2e-goerli:
    <<: *monitor-e2e-base
    environment:
      CHAIN_ID: 5
      CHAIN_NAME: goerli
  monitor-e2e-sepolia:
    <<: *monitor-e2e-base
    environment:
      CHAIN_ID: '11155111'
      CHAIN_NAME: sepolia
  verification-e2e-goerli:
    <<: *verification-e2e-base
    environment:
      CHAIN_ID: 5
      CHAIN_NAME: goerli
  verification-e2e-sepolia:
    <<: *verification-e2e-base
    environment:
      CHAIN_ID: '11155111'
      CHAIN_NAME: sepolia
  check-s3-backup:
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install @aws-sdk/client-s3
      - run:
          name: backup test
          command: node --experimental-fetch ./scripts/check-s3-backup.mjs
    docker:
      - image: cimg/node:16.15
  check-etherscan-instances:
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npx lerna bootstrap
      - run:
          name: build
          command: npx lerna run build
      - run: 
          name: test
          command: npx mocha test/etherscan/etherscanInstances.js --exit
    docker:
      - image: cimg/node:16.15